// auth types
export const LOGIN_LOADING = "LOGIN_LOADING";
export const SIGN_UP_LOADING = "SIGN_UP_LOADING";
export const LOADING = "LOADING";

export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGN_UP_SUCCESSFULLY = "SIGN_UP_SUCCESSFULLY";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const LOGIN_STATUS_OK = "LOGIN_STATUS_OK";
export const LOGIN_STATUS_FAILED = "LOGIN_STATUS_FAILED";

export const LOGOUT_SUCCESSFULLY = "LOGOUT_SUCCESSFULLY";

// movie actions
export const MOVIE_LOADING = "MOVIE_LOADING";

export const FETCH_ALL_MOVIE_SUCCESS = "FETCH_ALL_MOVIE_SUCCESS";
export const FETCH_ALL_MOVIE_FAILED = "FETCH_ALL_MOVIE_FAILED";

export const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
export const RATE_MOVIE_FAILED = "RATE_MOVIE_FAILED";

export const FETCH_SELECTED_MOVIE_SUCCESS = "FETCH_SELECTED_MOVIE_SUCCESS";
export const FETCH_SELECTED_MOVIE_FAILED = "FETCH_SELECTED_MOVIE_FAILED";

export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILED = "DELETE_MOVIE_FAILED";

export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_FAILED = "EDIT_MOVIE_FAILED";

export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILED = "ADD_MOVIE_FAILED";


// saga requests //
// - auth requests
export const CHECK_LOGIN_STATUS_REQUEST = "CHECK_LOGIN_STATUS_REQUEST";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST";
// - movie requests
export const FETCH_ALL_MOVIE_REQUEST = "FETCH_ALL_MOVIE_REQUEST";
export const RATE_MOVIE_REQUEST = "RATE_MOVIE_REQUEST";
export const FETCH_SELECTED_MOVIE_REQUEST = "FETCH_SELECTED_MOVIE_REQUEST";
export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const EDIT_MOVIE_REQUEST = "EDIT_MOVIE_REQUEST";
export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
