// auth types
export const LOGIN_LOADING = "LOGIN_LOADING";
export const SIGN_UP_LOADING = "SIGN_UP_LOADING";
export const LOADING = "LOADING";

export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGN_UP_SUCCESSFULLY = "SIGN_UP_SUCCESSFULLY";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const LOGIN_STATUS_OK = "LOGIN_STATUS_OK";
export const LOGIN_STATUS_FAILED = "LOGIN_STATUS_FAILED";

export const LOGOUT_SUCCESSFULLY = "LOGOUT_SUCCESSFULLY";


// movie actions
export const MOVIE_LOADING = "MOVIE_LOADING";

export const FETCH_ALL_MOVIE_SUCCESS = "FETCH_ALL_MOVIE_SUCCESS";
export const FETCH_ALL_MOVIE_FAILED = "FETCH_ALL_MOVIE_FAILED";

export const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
export const RATE_MOVIE_FAILED = "RATE_MOVIE_FAILED";

export const FETCH_SELECTED_MOVIE_SUCCESS = "FETCH_SELECTED_MOVIE_SUCCESS";
export const FETCH_SELECTED_MOVIE_FAILED = "FETCH_SELECTED_MOVIE_FAILED";

export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILED = "DELETE_MOVIE_FAILED";

export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_FAILED = "EDIT_MOVIE_FAILED";

export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILED = "ADD_MOVIE_FAILED";